export type SeedProvenance =
  | 'self-saved'
  | 'commercial'
  | 'hobbyist'
  | 'md'

export type SeedStart = {
  variety: string
  crop: 'tomato'
  provenance: SeedProvenance
  generation?: string
  seedsStarted: number
  startedAt: string
  method: 'towel' | 'egg-tray'
}

export const tomatoSeedStarts: SeedStart[] = [
  // Self-saved seed
  {
    variety: 'Green Tiger',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '25-26',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Dr Wyches Yellow',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '23-24',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Bumble Bee Pink',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '23-24',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Bumble Bee Purple',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '25-26',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Blue Zimmer MD',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '23-24',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Cherokee Purple',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '25-26',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: "Barry's Crazy Cherry",
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '25-26',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Garden Peach',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '25-26',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: "Brad's Atomic Grape",
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '25-26',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Bumble Bee Sunrise',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '25-26',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: "Aunt Ruby's German Green",
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '23-24',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Ildi',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '25-26',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Principe Borghese',
    crop: 'tomato',
    provenance: 'self-saved',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Principe Borghese',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '25-26',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'egg-tray',
  },
  {
    variety: 'Vintage Vine',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '25-26',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Yellow / Orange MD',
    crop: 'tomato',
    provenance: 'self-saved',
    generation: '23-24',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },

  // Commercial packs
  {
    variety: 'Ananas Noir',
    crop: 'tomato',
    provenance: 'commercial',
    seedsStarted: 6,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Sungold',
    crop: 'tomato',
    provenance: 'commercial',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Berner Rose Tomato',
    crop: 'tomato',
    provenance: 'commercial',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'San Marzano',
    crop: 'tomato',
    provenance: 'commercial',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Black Strawberry',
    crop: 'tomato',
    provenance: 'commercial',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Costoluto Fiorentino',
    crop: 'tomato',
    provenance: 'commercial',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Purple Calabash',
    crop: 'tomato',
    provenance: 'commercial',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Midnight Roma',
    crop: 'tomato',
    provenance: 'commercial',
    seedsStarted: 10,
    startedAt: '2026-09-13',
    method: 'towel',
  },

  // Personal use / hobbyist bought
  {
    variety: 'Apricot',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 4,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Belgium Giant',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 4,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Berkeley Tie & Dye Green',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 4,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Blue Beauty',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 4,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Cuostralee',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 4,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Green Grape',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 4,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Kozula 128',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 2,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Pineapple',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 4,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Reise Tomato',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 4,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Rosella Tomato',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 4,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Ukrainian Tomato',
    crop: 'tomato',
    provenance: 'hobbyist',
    seedsStarted: 4,
    startedAt: '2026-09-13',
    method: 'towel',
  },

  // MD
  {
    variety: "Hardin's Miniature MD",
    crop: 'tomato',
    provenance: 'md',
    seedsStarted: 2,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Balcony Yellow MD',
    crop: 'tomato',
    provenance: 'md',
    seedsStarted: 2,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Orange Hat MD',
    crop: 'tomato',
    provenance: 'md',
    seedsStarted: 2,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Minibel MD',
    crop: 'tomato',
    provenance: 'md',
    seedsStarted: 2,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Borghese Vase Roman',
    crop: 'tomato',
    provenance: 'md',
    seedsStarted: 2,
    startedAt: '2026-09-13',
    method: 'towel',
  },
  {
    variety: 'Dwarf Boxer Rebellion CTR',
    crop: 'tomato',
    provenance: 'md',
    seedsStarted: 2,
    startedAt: '2026-09-13',
    method: 'towel',
  },
]